[package]
name = "lex"
version = "1.1.0"
authors = ["Thomas Castleman <thomascastleman0@gmail.com>"]
edition = "2021"
description = "A simple implementation of a lexer."
repository = "https://github.com/thomascastleman/lex"

[dependencies]
regex = "1"